In [ ]:
import pandas as pd 
tissuepositions = pd.read_parquet("data/CRC_P1/output/binned_outputs/square_008um/spatial/tissue_positions.parquet")

metadata = pd.read_parquet("data/CRC_P1/Metadata.parquet")

## Read the tissue positions and metadata file
This gives us information on the format of pixel value coordinates.
It also gives us an info on outliers and e.g. how many negative examples entries in the y-position-column there are.

In [8]:
tissuepositions

,barcode,in_tissue,array_row,array_col,pxl_row_in_fullres,pxl_col_in_fullres
0,s_008um_00000_00000-1,0,0,0,36591.694839,-242.091470
1,s_008um_00000_00001-1,0,0,1,36591.965228,-212.877209
2,s_008um_00000_00002-1,0,0,2,36592.235617,-183.662943
3,s_008um_00000_00003-1,0,0,3,36592.506006,-154.448672
4,s_008um_00000_00004-1,0,0,4,36592.776395,-125.234396
...,...,...,...,...,...,...
702239,s_008um_00837_00833-1,1,837,833,12357.868203,24323.438541
702240,s_008um_00837_00834-1,1,837,834,12358.136674,24352.657678
702241,s_008um_00837_00835-1,1,837,835,12358.405145,24381.876820
702242,s_008um_00837_00836-1,1,837,836,12358.673616,24411.095967
702243,s_008um_00837_00837-1,1,837,837,12358.942088,24440.315118

In [ ]:
# negative column values
negative_col = tissuepositions[tissuepositions["pxl_col_in_fullres"] < 0]
print("Negative pxl_col_in_fullres values:")
print(negative_col)

Negative pxl_col_in_fullres values:
                      barcode  in_tissue  array_row  array_col  \
0       s_008um_00000_00000-1          0          0          0
1       s_008um_00000_00001-1          0          0          1
2       s_008um_00000_00002-1          0          0          2
3       s_008um_00000_00003-1          0          0          3
4       s_008um_00000_00004-1          0          0          4
...                       ...        ...        ...        ...
698054  s_008um_00833_00000-1          0        833          0
698892  s_008um_00834_00000-1          0        834          0
699730  s_008um_00835_00000-1          0        835          0
700568  s_008um_00836_00000-1          0        836          0
701406  s_008um_00837_00000-1          0        837          0

        pxl_row_in_fullres  pxl_col_in_fullres
0             36591.694839         -242.091470
1             36591.965228         -212.877209
2             36592.235617         -183.662943
3             36592.506006         -154.448672
4             36592.776395         -125.234396
...                    ...                 ...
698054        12251.132105          -15.561726
698892        12221.910793          -15.289773
699730        12192.689479          -15.017819
700568        12163.468163          -14.745866
701406        12134.246844          -14.473913

[4096 rows x 6 columns]

In [17]:
# negative row values
negative_row = tissuepositions[tissuepositions["pxl_row_in_fullres"] < 0]
print("Negative pxl_row_in_fullres values:")
print(negative_row)

Negative pxl_row_in_fullres values:
Empty DataFrame
Columns: [barcode, in_tissue, array_row, array_col, pxl_row_in_fullres, pxl_col_in_fullres]
Index: []

In [ ]:
# check for negative col values, that are in tissue (not outside of tissue)
overlap_intissue = tissuepositions[(tissuepositions["pxl_col_in_fullres"] < 0) & (tissuepositions["in_tissue"] == 1)]
print("Overlap pxl_col_in_fullres < 0 and in_tissue == 1:")
print(overlap_intissue)

Overlap pxl_col_in_fullres > 0 and in_tissue == 1:
Empty DataFrame
Columns: [barcode, in_tissue, array_row, array_col, pxl_row_in_fullres, pxl_col_in_fullres]
Index: []

In [ ]:
# count all pixels in tissue
print(len(tissuepositions[tissuepositions["in_tissue"] == 0]))

194560

In [13]:
print("positive pixel values: ", len(tissuepositions[tissuepositions["pxl_col_in_fullres"] > 0]))
print("negative pixel values: ", len(tissuepositions[tissuepositions["pxl_col_in_fullres"] < 0]))
print("in_tissue == 1: ", len(tissuepositions[tissuepositions["in_tissue"] == 1]))
print("in_tissue == 0: ", len(tissuepositions[tissuepositions["in_tissue"] == 0]))

positive pixel values:  698148
negative pixel values:  4096
in_tissue == 1:  507684
in_tissue == 0:  194560

In [20]:
col = "pxl_col_in_fullres"
smallest_gt_zero = tissuepositions.loc[tissuepositions[col] > 0, col].min()
print(f"Smallest positive value in {col}: {smallest_gt_zero}")

smallest_gt_zero = tissuepositions.loc[tissuepositions[col] > 0, col].max()
print(f"Biggest positive value in {col}: {smallest_gt_zero}")

Smallest positive value in pxl_col_in_fullres: 0.01616907989636651
Biggest positive value in pxl_col_in_fullres: 24440.315118149927

In [22]:
row = "pxl_row_in_fullres"
smallest_gt_zero = tissuepositions.loc[tissuepositions[row] > 0, row].min()
print(f"Smallest positive value in {row}: {smallest_gt_zero}")

smallest_gt_zero = tissuepositions.loc[tissuepositions[row] > 0, row].max()
print(f"Biggest positive value in {row}: {smallest_gt_zero}")

Smallest positive value in pxl_row_in_fullres: 12134.246844050029
Biggest positive value in pxl_row_in_fullres: 36818.02543268167

In [4]:
metadata

,barcode,tissue,X,Y,DeconvolutionClass,DeconvolutionLabel1,DeconvolutionLabel2,Periphery,UnsupervisedL1,UnsupervisedL2,MacrophageSubtype,GobletSubcluster
0,s_008um_00000_00000-1,0,-2.042794,-308.764636,None,None,None,None,None,None,None,None
1,s_008um_00000_00001-1,0,-1.796281,-308.766918,None,None,None,None,None,None,None,None
2,s_008um_00000_00002-1,0,-1.549768,-308.769200,None,None,None,None,None,None,None,None
3,s_008um_00000_00003-1,0,-1.303254,-308.771481,None,None,None,None,None,None,None,None
4,s_008um_00000_00004-1,0,-1.056741,-308.773763,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
702239,s_008um_00837_00833-1,1,205.243777,-104.277014,None,None,None,Tissue,B cells,Bcells-0,None,None
702240,s_008um_00837_00834-1,1,205.490331,-104.279280,None,None,None,Tissue,Unknown,Unknown-2,None,None
702241,s_008um_00837_00835-1,1,205.736885,-104.281545,None,None,None,Tissue,B cells,Bcells-0,None,None
702242,s_008um_00837_00836-1,1,205.983440,-104.283810,None,None,None,Tissue,B cells,Bcells-0,None,None
702243,s_008um_00837_00837-1,1,206.229994,-104.286076,None,None,None,Tissue,B cells,Bcells-0,None,None

## Look at feature matrices

In [6]:
import h5py

# Raw feature matrix
print("RAW FEATURE MATRIX STRUCTURE:")
with h5py.File("data/CRC_P1/binned_outputs/square_008um/raw_feature_bc_matrix.h5", "r") as f:
    # Recursive function to print structure
    def print_structure(name, obj):
        print(name)

    f.visititems(print_structure)


# Filtered feature matrix
print("FILTERED FEATURE MATRIX STRUCTURE:")
with h5py.File("data/CRC_P1/binned_outputs/square_008um/filtered_feature_bc_matrix.h5", "r") as f:
    # Recursive function to print structure
    def print_structure(name, obj):
        print(name)

    f.visititems(print_structure)

RAW FEATURE MATRIX STRUCTURE:
matrix
matrix/barcodes
matrix/data
matrix/features
matrix/features/_all_tag_keys
matrix/features/feature_type
matrix/features/genome
matrix/features/id
matrix/features/name
matrix/features/target_sets
matrix/features/target_sets/Visium Human Transcriptome Probe Set v2.0
matrix/indices
matrix/indptr
matrix/shape
FILTERED FEATURE MATRIX STRUCTURE:
matrix
matrix/barcodes
matrix/data
matrix/features
matrix/features/_all_tag_keys
matrix/features/feature_type
matrix/features/genome
matrix/features/id
matrix/features/name
matrix/features/target_sets
matrix/features/target_sets/Visium Human Transcriptome Probe Set v2.0
matrix/indices
matrix/indptr
matrix/shape

In [17]:
import scanpy as sc
import squidpy as sq

/home/charlotte/miniconda3/envs/genomosaic/lib/python3.10/site-packages/dask/dataframe/__init__.py:31: FutureWarning: The legacy Dask DataFrame implementation is deprecated and will be removed in a future version. Set the configuration option `dataframe.query-planning` to `True` or None to enable the new Dask Dataframe implementation and silence this warning.
  warnings.warn(
/home/charlotte/miniconda3/envs/genomosaic/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)

In [20]:
test_=sq.read.visium("/home/charlotte/Documents/Arbeit/Genomosaic/data/CRC_P1/binned_outputs/square_008um",counts_file="/home/charlotte/Documents/Arbeit/Genomosaic/data/CRC_P1/binned_outputs/square_008um/filtered_feature_bc_matrix.h5",)

/home/charlotte/miniconda3/envs/genomosaic/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/charlotte/miniconda3/envs/genomosaic/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

FileNotFoundError: [Errno 2] No such file or directory: '/home/charlotte/Documents/Arbeit/Genomosaic/data/CRC_P1/binned_outputs/square_008um/spatial/tissue_positions_list.csv'

In [22]:
from spatialdata_io import visium_hd

/home/charlotte/miniconda3/envs/genomosaic/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)

In [ ]:
sdata = visium_hd(
    path="data/CRC_P1/output",            # directory with HD outputs
    dataset_id="Visium_HD_Human_Colon_Cancer_P1",
    filtered_counts_file=True,           # uses filtered counts; set False for raw
    bin_size=8,                        # loads all bin levels; you can pick [2,8,16]
    fullres_image_file="data/CRC_P1/input/Visium_HD_Human_Colon_Cancer_P1_image.btf",  # path to full resolution image
)

/home/charlotte/miniconda3/envs/genomosaic/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [28]:
sdata

SpatialData object
├── Images
│     ├── 'Visium_HD_Human_Colon_Cancer_P1_full_image': DataTree[cyx] (3, 4961, 6000), (3, 2480, 3000), (3, 1240, 1500), (3, 620, 750), (3, 310, 375)
│     ├── 'Visium_HD_Human_Colon_Cancer_P1_hires_image': DataArray[cyx] (3, 4961, 6000)
│     └── 'Visium_HD_Human_Colon_Cancer_P1_lowres_image': DataArray[cyx] (3, 496, 600)
├── Shapes
│     └── 'Visium_HD_Human_Colon_Cancer_P1_square_008um': GeoDataFrame shape: (507684, 1) (2D shapes)
└── Tables
      └── 'square_008um': AnnData (507684, 18085)
with coordinate systems:
    ▸ 'Visium_HD_Human_Colon_Cancer_P1', with elements:
        Visium_HD_Human_Colon_Cancer_P1_full_image (Images), Visium_HD_Human_Colon_Cancer_P1_hires_image (Images), Visium_HD_Human_Colon_Cancer_P1_lowres_image (Images), Visium_HD_Human_Colon_Cancer_P1_square_008um (Shapes)
    ▸ 'Visium_HD_Human_Colon_Cancer_P1_downscaled_hires', with elements:
        Visium_HD_Human_Colon_Cancer_P1_hires_image (Images), Visium_HD_Human_Colon_Cancer_P1_square_008um (Shapes)
    ▸ 'Visium_HD_Human_Colon_Cancer_P1_downscaled_lowres', with elements:
        Visium_HD_Human_Colon_Cancer_P1_lowres_image (Images), Visium_HD_Human_Colon_Cancer_P1_square_008um (Shapes)

In [31]:
ff=sc.read_10x_h5('data/CRC_P1/output/binned_outputs/square_008um/filtered_feature_bc_matrix.h5')

/home/charlotte/miniconda3/envs/genomosaic/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/charlotte/miniconda3/envs/genomosaic/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [34]:
ff

AnnData object with n_obs × n_vars = 507684 × 18085
    var: 'gene_ids', 'feature_types', 'genome'

In [1]:
import pandas as pd
results = pd.read_csv("Cell_Segmentation/output/CRC_P1/Nuclei_Barcode_Map.csv")

In [4]:
# Count occurrences of each id
id_count_check = len(results["id"].unique())
id_count = results["id"].value_counts()
print("Unique IDs found in the results:", id_count_check)  # List of unique IDs
print("Counts of each ID:", id_count)  # Counts of each ID

# Filter brands that occur more than once
ids_more_than_once = id_count[id_count > 1]

# If you want just the list of brand names:
id_label = ids_more_than_once.index.tolist()

# If you want the number of such brands:
number_of_ids = len(ids_more_than_once)

print("IDs appearing more than once:")
print(ids_more_than_once)       # brand name and counts
#print(id_label)                 # just brand names
print("Number of Ids: ", number_of_ids)           # count of brands appearing more than once

Unique IDs found in the results: 110016
Counts of each ID: id
ID_85299     7
ID_534315    5
ID_381216    5
ID_84659     5
ID_276597    5
            ..
ID_391996    1
ID_390550    1
ID_391503    1
ID_390132    1
ID_388651    1
Name: count, Length: 110016, dtype: int64
IDs appearing more than once:
id
ID_85299     7
ID_534315    5
ID_381216    5
ID_84659     5
ID_276597    5
            ..
ID_54843     2
ID_535021    2
ID_531992    2
ID_401223    2
ID_540878    2
Name: count, Length: 3687, dtype: int64
Number of Ids:  3687

In [1]:
import pandas as pd
df1 = pd.read_csv("uni/notebooks/metadata/WSI_patch_metadata1.csv")
df2 = pd.read_csv("uni/notebooks/metadata/WSI_patch_metadata2.csv")

merged_df = pd.concat([df1, df2], axis=0, ignore_index=True)

merged_df.to_csv("uni/notebooks/metadata/WSI_patch_metadata.csv", index=False)

In [2]:
import scanpy as sc
import anndata as ad

# Load both .h5ad files
adata1 = sc.read_h5ad("uni/notebooks/metadata/WSI_patch_embeddings1.h5ad")
adata2 = sc.read_h5ad("uni/notebooks/metadata/WSI_patch_embeddings2.h5ad")

# Concatenate along observations (rows)
adata_merged = ad.concat([adata1, adata2], axis=0, join="outer")  
# join="outer" keeps all obs/var, join="inner" keeps only common

# Save
adata_merged.write_h5ad("uni/notebooks/metadata/WSI_patch_embeddings.h5ad")

In [4]:
adata_merged

AnnData object with n_obs × n_vars = 57435 × 1536
    obs: 'Slide_ID', 'Patch_ID', 'X', 'Y'
    obsm: 'spatial'

In [5]:
people = adata_merged.obs["Slide_ID"].unique()

In [8]:
print(adata_merged.obs)

                            Slide_ID         Patch_ID      X      Y
CRC_P1_patch_1.png            CRC_P1      patch_1.png      0      0
CRC_P1_patch_2.png            CRC_P1      patch_2.png      0    224
CRC_P1_patch_3.png            CRC_P1      patch_3.png      0    448
CRC_P1_patch_4.png            CRC_P1      patch_4.png      0    672
CRC_P1_patch_5.png            CRC_P1      patch_5.png      0    896
...                              ...              ...    ...    ...
Normal_P5_patch_11877.png  Normal_P5  patch_11877.png  24192  23296
Normal_P5_patch_11878.png  Normal_P5  patch_11878.png  24192  23520
Normal_P5_patch_11879.png  Normal_P5  patch_11879.png  24192  23744
Normal_P5_patch_11880.png  Normal_P5  patch_11880.png  24192  23968
Normal_P5_patch_11881.png  Normal_P5  patch_11881.png  24192  24192

[57435 rows x 4 columns]